// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema_Control_Taller_Bicicletas.Data;

#nullable disable

namespace Sistema_Control_Taller_Bicicletas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261009160551_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sistema_Control_Taller_Bicicletas.Models.Bicicleta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroSerie")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Bicicletas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteId = 1,
                            Color = "Negro / Azul",
                            Descripcion = "Bicicleta de montaña, uso urbano y fin de semana. Requiere cambio de frenos traseros y lubricación general.",
                            FechaIngreso = new DateTime(2026, 9, 28, 8, 0, 0, 0, DateTimeKind.Local),
                            Marca = "Giant",
                            Modelo = "Talon 3 29",
                            NumeroSerie = "GN2024-000123"
                        },
                        new
                        {
                            Id = 2,
                            ClienteId = 2,
                            Color = "Blanco",
                            Descripcion = "Híbrida, se trae por ajuste de cambios delanteros y servicio completo (limpieza + lubricación).",
                            FechaIngreso = new DateTime(2026, 10, 1, 9, 15, 0, 0, DateTimeKind.Local),
                            Marca = "Trek",
                            Modelo = "Dual Sport 2",
                            NumeroSerie = "TRK-DS2-88421"
                        },
                        new
                        {
                            Id = 3,
                            ClienteId = 1,
                            Color = "Rojo",
                            Descripcion = "Bicicleta de ruta. Ruido en pedalier, se sospecha rodamientos desgastados.",
                            FechaIngreso = new DateTime(2026, 10, 3, 11, 0, 0, 0, DateTimeKind.Local),
                            Marca = "Specialized",
                            Modelo = "Allez Sport",
                            NumeroSerie = "SP-ALZ-SP-33190"
                        },
                        new
                        {
                            Id = 4,
                            ClienteId = 3,
                            Color = "Verde",
                            Descripcion = "MTB 29. Revisión general luego de 6 meses sin uso. Cambio de cableado completo.",
                            FechaIngreso = new DateTime(2026, 10, 5, 13, 45, 0, 0, DateTimeKind.Local),
                            Marca = "Scott",
                            Modelo = "Aspect 950",
                            NumeroSerie = "SC-ASP950-22107"
                        },
                        new
                        {
                            Id = 5,
                            ClienteId = 2,
                            Color = "Gris",
                            Descripcion = "Bicicleta de ciudad del usuario menor. Ajuste de altura de manubrio y asiento, más protectores de plato.",
                            FechaIngreso = new DateTime(2026, 10, 6, 16, 20, 0, 0, DateTimeKind.Local),
                            Marca = "Merida",
                            Modelo = "Ride 200",
                            NumeroSerie = "MR-RD200-55731"
                        });
                });

            modelBuilder.Entity("Sistema_Control_Taller_Bicicletas.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Pérez",
                            Direccion = "Calle Duarte #12, Santo Domingo",
                            Email = "juan.perez@example.com",
                            FechaRegistro = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Juan",
                            Telefono = "809-555-1001"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Gómez",
                            Direccion = "Av. 27 de Febrero #45, Santiago",
                            Email = "maria.gomez@example.com",
                            FechaRegistro = new DateTime(2026, 2, 10, 10, 30, 0, 0, DateTimeKind.Local),
                            Nombre = "María",
                            Telefono = "809-555-1002"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Rodríguez",
                            Direccion = "Calle San Juan #8, La Vega",
                            Email = "carlos.rodriguez@example.com",
                            FechaRegistro = new DateTime(2026, 3, 5, 14, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Carlos",
                            Telefono = "809-555-1003"
                        });
                });

            modelBuilder.Entity("Sistema_Control_Taller_Bicicletas.Models.Bicicleta", b =>
                {
                    b.HasOne("Sistema_Control_Taller_Bicicletas.Models.Cliente", "Cliente")
                        .WithMany("Bicicletas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Sistema_Control_Taller_Bicicletas.Models.Cliente", b =>
                {
                    b.Navigation("Bicicletas");
                });
#pragma warning restore 612, 618
        }
    }
}
